### ISSUE TITLE
Update weather

### ISSUE THREAD

**Issue by daniel-naegele** [PlugaruT/wingpanel-monitor#7]
Hi,
I really like your wingpanel monitor, it is really good. But the problem is, that the weather only gets updated, if I click on 'Open Settings'. Would it be possible to periodically update it or set up a cron job to do this?

With kind regards,
Butzlabben

**Comment by PlugaruT** [comment]
Hey, yes, I've noticed this problem and you are right. 
I am working on a solution for this issue.

**Comment by PlugaruT** [comment]
I've pushed a fix for this issue. Can you please check and see if it works please.

**Comment by PlugaruT** [comment]
The weather should get updated every 15 minutes. 
I am working on a solution to make this value configurable

**Comment by daniel-naegele** [comment]
It seems to be updating now regularly, but the temperature is not very accurate. What API do you use?

**Comment by PlugaruT** [comment]
I am using [gweather](https://valadoc.org/gweather-3.0/GWeather.html) for this.
Right now I am working on this to make it more reliable

**Comment by casasfernando** [comment]
@Butzlabben I forked @PlugaruT 's  project to https://github.com/casasfernando/wingpanel-indicator-weather as a dedicated weather indicator, fixed this problem, did some modifications and add a few features (including manual location setting). You can also find a Debian package in the release page for easy installation.

I hope you find it useful, and many thanks for @PlugaruT since his code was a great base to work on.
